math_project/accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns =[
  
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name= 'user_register_verify_code'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'), 


    path('reset_password/',views.ResetPasswordView.as_view(), name='reset_password'),
    path('otp_reset_password/', views.OtpResetPasswordView.as_view(), name='otp_reset_password'),
    path('forgot_password/', views.UserForgotpasswordView.as_view(), name='forgot_password')




  
    
]

math_project/math_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('question/', include('question.urls', namespace='question')),
]

math_project/web/urls.py
from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

math_project/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'web:home' %}">Home</a>
            <!-- {% if request.user.is_authenticated %} <a class="nav-link active" ––>-->
            href="{% url 'accounts:user_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
            <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
            {% endif %}


        </div>
    </div>
</nav>